[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "mnist"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/tui", "burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu", "burn/fusion"]
metal = ["burn/metal", "burn/fusion"]
remote = ["burn/remote"]

[dependencies]
# Disable autotune default for now (convolutions not optimized)
burn = { path = "../../crates/burn", features = [
    "train",
    "vision",
    "metrics",
    "std",
    "collective",
    "vision",
], default-features = false }

image = "0.25.0"  # or latest version

rand.workspace = true

# cubecl = { workspace = true, features = [
#     "matmul",
#     "convolution",
#     "reduce",
#     "random",
#     "stdlib",
# ] }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
